baseURL: "/"
disablePathToLower: true
languageCode: en-us
title: '@LucP'
description: 'Independent developer & designer. Open source lover, barbecue fan and hoping to write more.'
theme: hyde
hugo_version: 0.21